name = "graphql-openai-worker"
main = "server/src/index.ts"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Durable Objects 声明
[durable_objects]
bindings = [
  { name = "CHAT_STORE", class_name = "ChatStore" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatStore"]

# 环境变量 - 使用占位符以避免泄露敏感信息
[vars]
# 不要在这里放置实际的 API 密钥，而是使用占位符
OPENAI_API_KEY = ""  # 部署时替换为实际 API 密钥

# 开发环境配置
[env.dev]
vars = { ENVIRONMENT = "development" }

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }