name = "server-worker"
main = "server/src/index.ts"
compatibility_date = "2025-05-01"
workers_dev = true
compatibility_flags = ["nodejs_compat"]  # 添加Node.js兼容性标志

# KV 命名空间绑定
[[kv_namespaces]]
binding = "CHAT_SESSIONS_KV"
id = "20725fcb81744059ab77c255677e4b5c"

[observability.logs]
enabled = true

# 环境变量
[vars]
OPENAI_API_KEY = ""

# 添加定期清理任务的配置（可选）
[triggers]
crons = ["0 0 * * *"] # 每天凌晨执行一次清理