name = "graphql-openai-worker"
main = "server/src/index.ts"
compatibility_date = "2025-05-01"
workers_dev = true

# Durable Objects 声明
[durable_objects]
bindings = [
  { name = "CHAT_STORE", class_name = "ChatStore" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatStore"]

[observability.logs]
enabled = true

# 环境变量
[vars]
OPENAI_API_KEY = ""

# 开发环境配置
[env.dev]
vars = { ENVIRONMENT = "development" }

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }