name = "server-worker"
main = "server/src/index.ts"
compatibility_date = "2023-05-01"
workers_dev = true
compatibility_flags = ["nodejs_compat", "durable_object_sql"] 

# Durable Objects 声明
[[durable_objects.bindings]]
name = "CHAT_SESSIONS"
class_name = "ChatSessionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatSessionDO"]

[observability.logs]
enabled = true

# 环境变量
[vars]
OPENAI_API_KEY = ""